global_costmap:
  publish_voxel_map: true #
  global_frame: map_costed
  robot_base_frame: base_link
  update_frequency: 2.0
  static_map: true #true
  transform_tolerance: 0.5
  map_topic: map_costed